name: "build frontend "

on:
    workflow_dispatch:
      branches:
        - master
    # push:
    #   branches:
    #     - master

env: 
    FRONTEND_DOCKER_IMAGE: sheriffexcel/signoz-app

jobs:
    
    build-frontend-image:
        runs-on: ubuntu-latest

        steps:
          
          - name: Checkout Codebase
            uses: actions/checkout@v4


          - uses: mr-smithers-excellent/docker-build-push@v6
            name: Build frontend Image
            with:
              image: ${{ env.FRONTEND_DOCKER_IMAGE }}
              tags: latest
              directory: ./frontend/
              dockerfile: ./frontend/Dockerfile
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}


  

          